
package es.udc.mashup.internalservice.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 09:55 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InternalServerProvider", targetNamespace = "http://ws.adoo.udc.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InternalServerProvider {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.mashup.internalservice.wsdl.InternalProductOutput>
     * @throws IncorrectInternalSearchException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchProductsBetweenDates", targetNamespace = "http://ws.adoo.udc.es/", className = "es.udc.mashup.internalservice.wsdl.SearchProductsBetweenDates")
    @ResponseWrapper(localName = "searchProductsBetweenDatesResponse", targetNamespace = "http://ws.adoo.udc.es/", className = "es.udc.mashup.internalservice.wsdl.SearchProductsBetweenDatesResponse")
    public List<InternalProductOutput> searchProductsBetweenDates(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5)
        throws IncorrectInternalSearchException
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.mashup.internalservice.wsdl.InternalProductOutput>
     * @throws IncorrectInternalSearchException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchProducts", targetNamespace = "http://ws.adoo.udc.es/", className = "es.udc.mashup.internalservice.wsdl.SearchProducts")
    @ResponseWrapper(localName = "searchProductsResponse", targetNamespace = "http://ws.adoo.udc.es/", className = "es.udc.mashup.internalservice.wsdl.SearchProductsResponse")
    public List<InternalProductOutput> searchProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3)
        throws IncorrectInternalSearchException
    ;

}
