
package es.udc.ws.jaxwstutorial.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 09:55 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "IncorrectTickerSymbolException", targetNamespace = "http://ws.adoo.udc.es/")
public class IncorrectTickerSymbolException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IncorrectTickerSymbolExceptionInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IncorrectTickerSymbolException(String message, IncorrectTickerSymbolExceptionInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IncorrectTickerSymbolException(String message, IncorrectTickerSymbolExceptionInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.udc.ws.jaxwstutorial.wsdl.IncorrectTickerSymbolExceptionInfo
     */
    public IncorrectTickerSymbolExceptionInfo getFaultInfo() {
        return faultInfo;
    }

}
