
package es.udc.ws.jaxwstutorial.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 09:55 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InternalServerProvider", targetNamespace = "http://ws.adoo.udc.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InternalServerProvider {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.ws.jaxwstutorial.wsdl.InternalProduct>
     * @throws IncorrectInternalSearchException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastTradePrices", targetNamespace = "http://ws.adoo.udc.es/", className = "es.udc.ws.jaxwstutorial.wsdl.GetLastTradePrices")
    @ResponseWrapper(localName = "getLastTradePricesResponse", targetNamespace = "http://ws.adoo.udc.es/", className = "es.udc.ws.jaxwstutorial.wsdl.GetLastTradePricesResponse")
    public List<InternalProduct> getLastTradePrices(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0)
        throws IncorrectInternalSearchException
    ;

}
